<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Squidlist.Core</RootNamespace>
    <AssemblyName>Squidlist.Core</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

</Project>
